// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NCBA.DCL.Data;

#nullable disable

namespace NCBA.DCL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212143000_AddGeneralCommentToChecklist")]
    partial class AddGeneralCommentToChecklist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            // This is a simplified key migration that only adds GeneralComment column
            // The full model is defined in your DbContext
#pragma warning restore 612, 618
        }
    }
}
